const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Run 31458853552 (with PR #115's DetoxTest.java stub) got further than
// ever: the stub was discovered, Detox.runTests() actually started, and
// the on-device logcat showed exactly why it then hung for the full 2
// minutes -- Detox's own native client endlessly retrying its local
// bridge connection:
//
//   Detox: Connecting to server...
//   DetoxWSClient: At connectToServer
//   DetoxWSClient: Retrying... (every ~3s, forever)
//
// `adb reverse tcp:<port> tcp:<port>` was confirmed set up correctly on
// the host side -- the connection is being refused at the Android OS
// level. Android blocks all cleartext (unencrypted, i.e. `ws://` not
// `wss://`) traffic by default for apps targeting API 28+, and Detox's
// local host<->device bridge is plain `ws://localhost:<port>` by design
// (it's a loopback-only test harness channel, not real app traffic).
// android/app/src/debug/AndroidManifest.xml already carries
// usesCleartextTraffic="true" for exactly this reason (Metro's dev
// server also needs cleartext localhost access) -- but Detox's Android
// build instruments the *release* build type (see .detoxrc.js and
// withDetoxTestBuildType.js's testBuildType override), which has no such
// override and falls back to the OS default (blocked).
//
// This can't just be added unconditionally to the release manifest: this
// project's Android build only exists via two paths that both run
// `expo prebuild` -- this repo's own CI-only Detox build (a throwaway
// APK, installed on an ephemeral emulator and discarded) and Stage 3's
// real shippable build (mobile-build.yml, which since it moved off EAS
// runs its own `expo prebuild` on the runner), which is what actually
// reaches users. Weakening the real app's cleartext-traffic protection
// to fix a CI-only test harness would be a real, if narrow, security
// regression. Gating this behind an environment variable that only
// mobile-detox.yml's prebuild step sets keeps Stage 3's prebuild (which
// never sets it) completely unaffected -- the override only ever applies
// to the disposable, CI-only build. Verified on the first real Stage 3
// APK: `usesCleartextTraffic` is absent from its AndroidManifest.
module.exports = function withDetoxReleaseCleartext(config) {
  return withDangerousMod(config, [
    "android",
    (config) => {
      if (process.env.DETOX_ANDROID_RELEASE_CLEARTEXT !== "1") return config;

      const dir = path.join(config.modRequest.platformProjectRoot, "app/src/release");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, "AndroidManifest.xml"),
        `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <!-- Generated by plugins/withDetoxReleaseCleartext.js, only when
         DETOX_ANDROID_RELEASE_CLEARTEXT=1 is set. See that file for why
         this exists. Scoped to the release build type Detox instruments,
         never applied to Stage 3's real shippable build. -->
    <application android:usesCleartextTraffic="true" tools:targetApi="28" tools:replace="android:usesCleartextTraffic" />
</manifest>
`
      );
      return config;
    },
  ]);
};
