const { withAppBuildGradle } = require("@expo/config-plugins");

// Points the `release` build type at a real upload keystore, so the AAB
// produced by mobile-release.yml is something the Play Store will accept.
//
// Expo's prebuild template wires `release` up to `signingConfigs.debug`
// (the standard Android debug keystore, password "android", shipped with
// every SDK install). That is deliberate on Expo's part -- it makes
// `assembleRelease` work out of the box for sideloading, which is exactly
// what mobile-build.yml (Stage 3) relies on -- but Play rejects anything
// signed with it, since every developer on earth holds the same key.
//
// android/ is generated by prebuild and not committed, so the signing
// config can't just be edited into build.gradle by hand; it has to be
// injected here, the same way the withDetox* plugins inject their own
// Gradle changes.
//
// Two design choices worth stating, because the obvious implementations
// are both worse:
//
//   * This APPENDS a second `android { }` block rather than rewriting the
//     existing one. Gradle merges repeated extension blocks, and
//     `buildTypes { release { ... } }` re-opens the build type that's
//     already there and overrides only the one property named -- so the
//     rest of the generated release config (minifyEnabled,
//     shrinkResources, proguard rules) is untouched. The alternative,
//     regex-replacing `signingConfig signingConfigs.debug` inside the
//     release block, has to distinguish it from the identical line in the
//     debug block and re-breaks every time Expo reformats its template.
//
//   * Credentials arrive as Gradle *project properties*, not literals.
//     mobile-release.yml sets them as ORG_GRADLE_PROJECT_* environment
//     variables, which Gradle maps to properties of the same name. That
//     keeps the keystore passwords out of the process argv (where a `-P`
//     flag would put them, visible to anything that can list processes on
//     the runner) and out of the repo entirely.
//
// The whole block is conditional on FATHOM_UPLOAD_STORE_FILE being set.
// When it isn't -- every local build, mobile-build.yml, and Stage 2's
// Detox release build -- nothing changes and `release` keeps its debug
// signing. So this plugin is inert for every existing workflow; only the
// store pipeline opts in, by supplying the credentials.
const SIGNING_BLOCK = `
// Injected by mobile/plugins/withReleaseSigning.js -- see that file for why
// this is appended rather than edited into the android block above.
// Inert unless FATHOM_UPLOAD_STORE_FILE is supplied (mobile-release.yml).
if (project.hasProperty('FATHOM_UPLOAD_STORE_FILE')) {
    android {
        signingConfigs {
            release {
                storeFile file(project.property('FATHOM_UPLOAD_STORE_FILE'))
                storePassword project.property('FATHOM_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('FATHOM_UPLOAD_KEY_ALIAS')
                keyPassword project.property('FATHOM_UPLOAD_KEY_PASSWORD')
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.release
            }
        }
    }
}
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.contents.includes("FATHOM_UPLOAD_STORE_FILE")) return config;
    config.modResults.contents += SIGNING_BLOCK;
    return config;
  });
};
