const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// Detox's own Javadoc (node_modules/detox/android/detox/src/full/java/com/wix/
// detox/Detox.java) spells out the missing piece: "To start Detox tests, call
// runTests() from a JUnit test" -- a single instrumented test class, annotated
// with @RunWith(AndroidJUnit4.class), whose one @Test method just calls
// Detox.runTests(activityRule) and blocks until the host-driven Jest session
// finishes. Bare React Native's `detox init` scaffolds this file automatically
// into the project's committed android/; Expo's prebuild regenerates
// android/ from scratch every time, and nothing was ever creating it.
//
// Without it, androidx.test.runner.AndroidJUnitRunner (correctly configured
// as of withDetoxTestBuildType.js) has no @Test-annotated class to discover
// at all -- confirmed on a real run (mobile-detox.yml run 31457925824) via
// `am instrument`'s own result: "OK (0 tests)" -- the exact same false-
// positive signature that originally revealed Stage 2 was never running any
// real test logic, this time for a new, distinct reason (a genuinely missing
// stub class, not a bypassed detox test process).
//
// androidx.test.ext:junit (for AndroidJUnit4) and androidx.test:rules (for
// ActivityTestRule) are already on the androidTest classpath as transitive
// `api` dependencies of the :detox module itself (see withDetoxAndroidModule.js
// and node_modules/detox/android/detox/build.gradle) -- no separate dependency
// needed here, just the missing source file.
module.exports = function withDetoxTestStub(config) {
  return withDangerousMod(config, [
    "android",
    (config) => {
      const packageName = config.android.package;
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/androidTest/java",
        ...packageName.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, "DetoxTest.java"),
        `package ${packageName};

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.filters.LargeTest;
import androidx.test.rule.ActivityTestRule;

import com.wix.detox.Detox;

import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

// Generated by plugins/withDetoxTestStub.js on every \`expo prebuild\` --
// see that file for why this exists. Mirrors Detox's own documented
// example verbatim (Detox.java's class-level Javadoc).
@RunWith(AndroidJUnit4.class)
@LargeTest
public class DetoxTest {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);

    @Test
    public void runDetoxTests() {
        Detox.runTests(mActivityRule);
    }
}
`
      );
      return config;
    },
  ]);
};
