export const tooltipStyle = {
  background: "var(--surface)",
  border: "1px solid var(--border)",
  borderRadius: 6,
  color: "var(--text)",
  fontFamily: "var(--font-body)",
  fontSize: 12,
};

export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg)",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    padding: "24px 20px 60px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    maxWidth: 900,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid var(--border)",
    paddingBottom: 16,
    gap: 12,
  },
  brand: {
    fontFamily: "var(--font-body)",
    fontSize: 32,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    textAlign: "center",
  },
  queryBar: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  inputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "10px 14px",
  },
  input: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 14,
  },
  askBtn: {
    background: "var(--accent)",
    color: "var(--bg)",
    border: "none",
    borderRadius: 7,
    padding: "7px 16px",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  feed: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  card: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 18,
  },
  cardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  qLabel: {
    color: "var(--text-muted)",
    fontSize: 12,
    fontFamily: "var(--font-body)",
    fontStyle: "italic",
  },
  titleLine: {
    fontFamily: "var(--font-body)",
    fontSize: 19,
    marginTop: 3,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-faint)",
    fontSize: 18,
    cursor: "pointer",
    lineHeight: 1,
  },
  chartWrap: {
    marginBottom: 14,
    position: "relative",
  },
  filterChip: {
    position: "absolute",
    top: 0,
    right: 0,
    background: "var(--surface-recessed)",
    border: "1px solid var(--accent)",
    color: "var(--text)",
    fontSize: 11,
    fontFamily: "var(--font-body)",
    padding: "3px 10px",
    borderRadius: 20,
  },
  chipX: {
    marginLeft: 8,
    cursor: "pointer",
    color: "var(--danger)",
  },
  listWrap: {
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
    maxHeight: 420,
    overflowY: "auto",
    overflowX: "hidden",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    tableLayout: "fixed",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontFamily: "var(--font-body)",
    padding: "0 6px 8px 6px",
    borderBottom: "1px solid var(--border)",
    position: "sticky",
    top: 0,
    background: "var(--surface)",
  },
  td: {
    padding: "8px 6px",
    borderBottom: "1px solid var(--border-subtle)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tag: {
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 20,
    fontFamily: "var(--font-body)",
  },
  // Numeric/data columns (dates, amounts, coordinates) get the monospace
  // face and tabular figures so digits line up in columns — same
  // convention as the location app's route table.
  mono: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
  },
  themeToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 30,
    height: 30,
    borderRadius: "50%",
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-faint)",
    cursor: "pointer",
  },
};
