export const tooltipStyle = {
  background: "var(--surface)",
  border: "1px solid var(--border)",
  borderRadius: 6,
  color: "var(--text)",
  fontFamily: "var(--font-body)",
  fontSize: 12,
};

export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg)",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    padding: "24px 20px 60px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    maxWidth: 900,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid var(--border)",
    paddingBottom: 16,
    gap: 12,
    rowGap: 10,
  },
  brand: {
    fontFamily: "var(--font-body)",
    fontSize: 32,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    textAlign: "center",
  },
  queryBar: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  // Home-screen account-balances strip: same card shell as everything else
  // (styles.card), one chip per linked account so multiple accounts list
  // side by side instead of collapsing into a single total.
  balancesCard: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: "14px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  balancesLabel: {
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontFamily: "var(--font-body)",
  },
  balancesRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  balanceChip: {
    background: "var(--surface-recessed)",
    borderRadius: 10,
    padding: "10px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 140,
    flex: "1 1 140px",
  },
  balanceChipLabel: {
    color: "var(--text-muted)",
    fontSize: 11,
    fontFamily: "var(--font-body)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  balanceChipAmount: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
    fontSize: 19,
    fontWeight: 600,
  },
  inputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "10px 14px",
  },
  input: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 14,
  },
  askBtn: {
    background: "var(--accent)",
    color: "var(--bg)",
    border: "none",
    borderRadius: 7,
    padding: "7px 16px",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  feed: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  card: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 18,
  },
  cardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  qLabel: {
    color: "var(--text-muted)",
    fontSize: 12,
    fontFamily: "var(--font-body)",
    fontStyle: "italic",
  },
  titleLine: {
    fontFamily: "var(--font-body)",
    fontSize: 19,
    marginTop: 3,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-faint)",
    fontSize: 18,
    cursor: "pointer",
    lineHeight: 1,
  },
  chartWrap: {
    marginBottom: 14,
    position: "relative",
  },
  filterChip: {
    position: "absolute",
    top: 0,
    right: 0,
    background: "var(--surface-recessed)",
    border: "1px solid var(--accent)",
    color: "var(--text)",
    fontSize: 11,
    fontFamily: "var(--font-body)",
    padding: "3px 10px",
    borderRadius: 20,
  },
  chipX: {
    marginLeft: 8,
    cursor: "pointer",
    color: "var(--danger)",
  },
  listWrap: {
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
    maxHeight: 420,
    overflowY: "auto",
    overflowX: "hidden",
  },
  // Two-line transaction row: payee (wraps rather than truncates) + the
  // category icon and amount pinned to the right on the first line, date
  // in a smaller muted font on the second -- keeps every field on screen
  // without horizontal scrolling or ellipsis clipping on narrow/mobile
  // widths, unlike the fixed-width table this replaced.
  txRow: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    padding: "6px 6px",
    borderBottom: "1px solid var(--border-subtle)",
    fontFamily: "var(--font-body)",
  },
  txRowTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  txPayee: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    color: "var(--text)",
    wordBreak: "break-word",
  },
  txRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  // Fixed width + right-aligned so the amount's digit count (e.g. "-$2.64"
  // vs "-$5,580.20") never shifts the category icon that precedes it --
  // without this the icon column drifts left/right per row.
  txAmount: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
    fontSize: 14,
    fontWeight: 600,
    whiteSpace: "nowrap",
    minWidth: 84,
    textAlign: "right",
  },
  txDate: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
    fontSize: 11,
    color: "var(--text-faint)",
  },
  txEmpty: {
    textAlign: "center",
    color: "var(--text-faint)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
    padding: "16px 0",
  },
  tag: {
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 20,
    fontFamily: "var(--font-body)",
  },
  // Icon-only category badge -- replaces the old text tag in the
  // transactions table so the column can shrink to just fit an icon,
  // leaving more room for Payee. The full category name is still
  // reachable via the icon's native title tooltip and the row-hover
  // detail popover, it's just not printed in the column itself.
  categoryIconBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    borderRadius: "50%",
  },
  // Floating panel shown on transaction-row hover with fields not already
  // visible in the row itself (Account, full Category). pointerEvents
  // "none" so it never steals the hover off the row it's describing, and
  // position "fixed" so it tracks the cursor regardless of scrolling
  // inside the (scrollable) listWrap.
  rowDetailPopover: {
    position: "fixed",
    zIndex: 50,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "10px 12px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.28)",
    fontFamily: "var(--font-body)",
    minWidth: 200,
    maxWidth: 260,
    pointerEvents: "none",
  },
  rowDetailTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text)",
    marginBottom: 6,
    paddingBottom: 6,
    borderBottom: "1px solid var(--border-subtle)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowDetailRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    padding: "2px 0",
  },
  rowDetailLabel: {
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    flexShrink: 0,
  },
  rowDetailValue: {
    color: "var(--text)",
    fontSize: 12,
    textAlign: "right",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerBtn: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 12px",
    color: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    fontSize: 12,
    cursor: "pointer",
  },
  // Persistent Home/Ask/Rules nav, rendered as real <a> tags (not buttons)
  // so Cmd/Ctrl-click and "open in new tab" behave like normal navigation
  // even though there's no router underneath -- click handling just
  // preventDefault()s and drives the same pushState logic.
  navRow: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  navLink: {
    display: "inline-block",
    background: "none",
    border: "1px solid transparent",
    borderRadius: 7,
    padding: "6px 12px",
    color: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    fontWeight: 500,
    textDecoration: "none",
    cursor: "pointer",
  },
  // Same "border" shorthand key as navLink (not a separate borderColor
  // longhand) -- mixing a shorthand with a longhand override across two
  // style objects that get conditionally merged left a stuck border color
  // once React cleared the longhand key between renders (falls back to
  // currentColor instead of the shorthand's original transparent).
  navLinkActive: {
    color: "var(--text)",
    border: "1px solid var(--border)",
    background: "var(--surface-recessed)",
  },
  pillRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  homePill: {
    background: "var(--surface-recessed)",
    border: "1px solid var(--border)",
    borderRadius: 20,
    padding: "8px 14px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    cursor: "pointer",
  },
  recentWrap: {
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "60px 20px",
    overflowY: "auto",
    zIndex: 100,
  },
  modalPanel: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 20,
    width: "100%",
    maxWidth: 640,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  modalHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    fontFamily: "var(--font-body)",
    fontSize: 19,
    fontWeight: 600,
  },
  ruleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    borderBottom: "1px solid var(--border-subtle)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
  },
  ruleRowText: {
    flex: 1,
    color: "var(--text)",
  },
  ruleDescription: {
    color: "var(--text-muted)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
    lineHeight: 1.5,
  },
  // Manual trigger for apply_category_rules() -- rules already reapply
  // automatically on add/toggle/delete, but a scrubbing-logic change
  // shipped separately (e.g. a new junk pattern added to clean_payee()
  // itself) needs an explicit way to re-run against existing history
  // without touching a rule.
  ruleReapplyBtn: {
    alignSelf: "flex-start",
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 12px",
    color: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    fontSize: 12,
    cursor: "pointer",
  },
  // Mirrors styles.listWrap (the transactions-table scroll pattern) so the
  // rules list gets the same scroll boundary once it grows past a screenful.
  ruleListWrap: {
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
    maxHeight: 320,
    overflowY: "auto",
    overflowX: "hidden",
  },
  ruleCheckbox: {
    accentColor: "var(--accent)",
    width: 15,
    height: 15,
    cursor: "pointer",
    flexShrink: 0,
  },
  ruleDeleteBtn: {
    background: "none",
    border: "none",
    color: "var(--text-faint)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    borderRadius: 6,
    flexShrink: 0,
  },
  ruleStatus: {
    color: "var(--accent)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
  },
  ruleError: {
    color: "var(--danger)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
  },
  ruleEmpty: {
    color: "var(--text-faint)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
  },
  ruleFormGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    background: "var(--surface-recessed)",
    borderRadius: 10,
    padding: 14,
  },
  ruleFormLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 13,
    fontFamily: "var(--font-body)",
    color: "var(--text-muted)",
  },
  formSelect: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
  },
  formInput: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    minWidth: 120,
    flex: 1,
  },
  formInputSmall: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    width: 70,
  },
  themeToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 30,
    height: 30,
    borderRadius: "50%",
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-faint)",
    cursor: "pointer",
  },
};
