export const tooltipStyle = {
  background: "var(--surface)",
  border: "1px solid var(--border)",
  borderRadius: 6,
  color: "var(--text)",
  fontFamily: "var(--font-body)",
  fontSize: 12,
};

export const styles = {
  page: {
    minHeight: "100vh",
    background: "var(--bg)",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    padding: "24px 20px 60px",
    display: "flex",
    flexDirection: "column",
    gap: 20,
    maxWidth: 900,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid var(--border)",
    paddingBottom: 16,
    gap: 12,
  },
  brand: {
    fontFamily: "var(--font-body)",
    fontSize: 32,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    textAlign: "center",
  },
  queryBar: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  // Home-screen account-balances strip: same card shell as everything else
  // (styles.card), one chip per linked account so multiple accounts list
  // side by side instead of collapsing into a single total.
  balancesCard: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: "14px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  balancesLabel: {
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontFamily: "var(--font-body)",
  },
  balancesRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
  },
  balanceChip: {
    background: "var(--surface-recessed)",
    borderRadius: 10,
    padding: "10px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 140,
    flex: "1 1 140px",
  },
  balanceChipLabel: {
    color: "var(--text-muted)",
    fontSize: 11,
    fontFamily: "var(--font-body)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  balanceChipAmount: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
    fontSize: 19,
    fontWeight: 600,
  },
  inputWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "10px 14px",
  },
  input: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 14,
  },
  askBtn: {
    background: "var(--accent)",
    color: "var(--bg)",
    border: "none",
    borderRadius: 7,
    padding: "7px 16px",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  feed: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  card: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 18,
  },
  cardHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
  },
  qLabel: {
    color: "var(--text-muted)",
    fontSize: 12,
    fontFamily: "var(--font-body)",
    fontStyle: "italic",
  },
  titleLine: {
    fontFamily: "var(--font-body)",
    fontSize: 19,
    marginTop: 3,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "var(--text-faint)",
    fontSize: 18,
    cursor: "pointer",
    lineHeight: 1,
  },
  chartWrap: {
    marginBottom: 14,
    position: "relative",
  },
  filterChip: {
    position: "absolute",
    top: 0,
    right: 0,
    background: "var(--surface-recessed)",
    border: "1px solid var(--accent)",
    color: "var(--text)",
    fontSize: 11,
    fontFamily: "var(--font-body)",
    padding: "3px 10px",
    borderRadius: 20,
  },
  chipX: {
    marginLeft: 8,
    cursor: "pointer",
    color: "var(--danger)",
  },
  listWrap: {
    borderTop: "1px solid var(--border)",
    paddingTop: 6,
    maxHeight: 420,
    overflowY: "auto",
    overflowX: "hidden",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    tableLayout: "fixed",
    fontSize: 13,
  },
  th: {
    textAlign: "left",
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontFamily: "var(--font-body)",
    padding: "0 6px 8px 6px",
    borderBottom: "1px solid var(--border)",
    position: "sticky",
    top: 0,
    background: "var(--surface)",
  },
  td: {
    padding: "8px 6px",
    borderBottom: "1px solid var(--border-subtle)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tag: {
    fontSize: 11,
    padding: "2px 8px",
    borderRadius: 20,
    fontFamily: "var(--font-body)",
  },
  // Icon-only category badge -- replaces the old text tag in the
  // transactions table so the column can shrink to just fit an icon,
  // leaving more room for Payee. The full category name is still
  // reachable via the icon's native title tooltip and the row-hover
  // detail popover, it's just not printed in the column itself.
  categoryIconBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    borderRadius: "50%",
  },
  // Numeric/data columns (dates, amounts, coordinates) get the monospace
  // face and tabular figures so digits line up in columns — same
  // convention as the location app's route table.
  mono: {
    fontFamily: "var(--font-mono)",
    fontVariantNumeric: "tabular-nums",
  },
  // Floating panel shown on table-row hover with every field the fixed
  // table columns don't have room for (Account, full Category, IsTransfer).
  // pointerEvents "none" so it never steals the hover off the row it's
  // describing, and position "fixed" so it tracks the cursor regardless of
  // scrolling inside the (scrollable) listWrap.
  rowDetailPopover: {
    position: "fixed",
    zIndex: 50,
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "10px 12px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.28)",
    fontFamily: "var(--font-body)",
    minWidth: 200,
    maxWidth: 260,
    pointerEvents: "none",
  },
  rowDetailTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text)",
    marginBottom: 6,
    paddingBottom: 6,
    borderBottom: "1px solid var(--border-subtle)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowDetailRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    padding: "2px 0",
  },
  rowDetailLabel: {
    color: "var(--text-muted)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    flexShrink: 0,
  },
  rowDetailValue: {
    color: "var(--text)",
    fontSize: 12,
    textAlign: "right",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerBtn: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 12px",
    color: "var(--text-muted)",
    fontFamily: "var(--font-body)",
    fontSize: 12,
    cursor: "pointer",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "60px 20px",
    overflowY: "auto",
    zIndex: 100,
  },
  modalPanel: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: 20,
    width: "100%",
    maxWidth: 640,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  modalHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    fontFamily: "var(--font-body)",
    fontSize: 19,
    fontWeight: 600,
  },
  ruleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 0",
    borderBottom: "1px solid var(--border-subtle)",
    fontSize: 13,
    fontFamily: "var(--font-body)",
  },
  ruleRowText: {
    flex: 1,
    color: "var(--text)",
  },
  ruleFormGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    background: "var(--surface-recessed)",
    borderRadius: 10,
    padding: 14,
  },
  ruleFormLine: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 13,
    fontFamily: "var(--font-body)",
    color: "var(--text-muted)",
  },
  formSelect: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
  },
  formInput: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    minWidth: 120,
    flex: 1,
  },
  formInputSmall: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "6px 10px",
    color: "var(--text)",
    fontFamily: "var(--font-body)",
    fontSize: 13,
    width: 70,
  },
  themeToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 30,
    height: 30,
    borderRadius: "50%",
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-faint)",
    cursor: "pointer",
  },
};
